// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuReaper.Infrastructure.Context;

#nullable disable

namespace NuReaper.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DependencyGraphId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependencyGraphId");

                    b.ToTable("Cycle");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.DependencyGraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPackage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalThreatLevel")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DependencyGraph");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.GraphEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DependencyGraphId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DependencyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFramework")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependencyGraphId");

                    b.ToTable("GraphEdge");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.GraphNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DependencyGraphId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependencyGraphId");

                    b.ToTable("GraphNode");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DependencyGraphId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LastScanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DependencyGraphId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.PackageDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTransitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFramework")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VersionRangeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VersionRangeId");

                    b.ToTable("PackageDependencies");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("ThreatLevel")
                        .HasColumnType("REAL");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.VersionRange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMaxInclusive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMinInclusive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaxVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MinVersion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VersionRange");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.Cycle", b =>
                {
                    b.HasOne("NuReaper.Domain.Entities.Graph.DependencyGraph", null)
                        .WithMany("Cycles")
                        .HasForeignKey("DependencyGraphId");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.GraphEdge", b =>
                {
                    b.HasOne("NuReaper.Domain.Entities.Graph.DependencyGraph", null)
                        .WithMany("Edges")
                        .HasForeignKey("DependencyGraphId");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.GraphNode", b =>
                {
                    b.HasOne("NuReaper.Domain.Entities.Graph.DependencyGraph", null)
                        .WithMany("Nodes")
                        .HasForeignKey("DependencyGraphId");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Package", b =>
                {
                    b.HasOne("NuReaper.Domain.Entities.Graph.DependencyGraph", "DependencyGraph")
                        .WithMany()
                        .HasForeignKey("DependencyGraphId");

                    b.Navigation("DependencyGraph");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.PackageDependency", b =>
                {
                    b.HasOne("NuReaper.Domain.Entities.VersionRange", "VersionRange")
                        .WithMany()
                        .HasForeignKey("VersionRangeId");

                    b.Navigation("VersionRange");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Scan", b =>
                {
                    b.HasOne("NuReaper.Domain.Entities.Package", null)
                        .WithMany("Scans")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Graph.DependencyGraph", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("NuReaper.Domain.Entities.Package", b =>
                {
                    b.Navigation("Scans");
                });
#pragma warning restore 612, 618
        }
    }
}
